### ISSUE TITLE
How to get multi audio ?

### ISSUE THREAD

**Issue by Shashank2406** [razorRun/react-native-vlc-media-player#25] opened 2020-08-07 11:31 UTC
I want to play 4k mkv file which runs fine, but can we control different audio ?

**Comment by razorRun** [comment] 2020-08-25 21:28
Well you can stream after fusing the video and audio you want ?

**Comment by razorRun** [comment] 2020-08-25 21:29
Closing this issue as this is not a bug

**Closed by razorRun** 2020-08-25 21:29 UTC
